// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MastheadItem interface {
	IsMastheadItem()
}

type AdvtItem struct {
	ID string `json:"id"`
}

func (AdvtItem) IsMastheadItem() {}

type ContentItem struct {
	ID   string `json:"id"`
	Test bool   `json:"test"`
}

func (ContentItem) IsMastheadItem() {}

type ContentItemWithScoreCard struct {
	ID string `json:"id"`
}

func (ContentItemWithScoreCard) IsMastheadItem() {}

type Masthead struct {
	ContentItems              []*ContentItem              `json:"contentItems"`
	ContentItemsWithScoreCard []*ContentItemWithScoreCard `json:"contentItemsWithScoreCard"`
	ScoreCards                []*ScoreCard                `json:"scoreCards"`
	AdvtItems                 []*AdvtItem                 `json:"advtItems"`
}

type ScoreCard struct {
	ID string `json:"id"`
}

func (ScoreCard) IsMastheadItem() {}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}
