// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ScoreCard struct {
	ID         string `json:"id"`
	TeamAScore int    `json:"teamAScore"`
	TeamBScore int    `json:"teamBScore"`
}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}
