// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdvtItem struct {
	ID         string `json:"id"`
	TrackerURL string `json:"trackerUrl"`
}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}
