---
apiVersion: v1
kind: Service
metadata:
  name: gql-apollo-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4004
  selector:
    app: gql-apollo-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-apollo-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-apollo-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gql-apollo-gateway
    spec:
      containers:
        - name: gql-apollo-gateway
          image: docker.io/ihac/apollo-gateway:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8096Mi"
              cpu: "8000m"
            limits:
              memory: "8096Mi"
              cpu: "8000m"
          ports:
            - name: http
              containerPort: 4004
