---
apiVersion: v1
kind: Service
metadata:
  name: gql-products
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4002
  selector:
    app: gql-products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gql-products
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gql-products
    spec:
      containers:
        - name: gql-products
          image: docker.io/ihac/products:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4002
