// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	Employees []*User `json:"employees"`
}

type NewCompany struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type NewUser struct {
	Name      string `json:"name"`
	Age       int    `json:"age"`
	CompanyID string `json:"companyId"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Age       int    `json:"age"`
	CompanyID string `json:"companyId"`
}
