---
apiVersion: v1
kind: Service
metadata:
  name: gql-accounts
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4001
  selector:
    app: gql-accounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gql-accounts
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gql-accounts
    spec:
      containers:
        - name: gql-accounts
          image: docker.io/ihac/accounts:1.0.0
          # imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 4001
