---
apiVersion: v1
kind: Service
metadata:
  name: gql-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4000
  selector:
    app: gql-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gql-gateway
    spec:
      containers:
        - name: gql-gateway
          image: docker.io/ihac/gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
