apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
        - name: shell
          image: docker.io/peterevans/vegeta
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "--"]
          args:
            - "while true; do echo hello; sleep 10; done"
